config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about", to: "public/homes#about"

  # 顧客用
  # URL /customers/...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  scope module: :public do
    resources :delivery_addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:show, :index]
    resources :cart_items, only: [:create, :index, :update, :destroy]
    delete "/cart_items/destroy_all", to: "cart_items#destroy_all"
    resources :orders, only: [:new, :create, :index, :show]
    get "/orders/comfirm", to: "order#/comfirm"
    get "/orders/complete", to: "orders#complete"
    get "/customers/my_page", to: "customers#show"
    get "/customers/information/edit", to: "customers#edit"
    patch "/customers/information", to: "customers#update"
    get "/customers/quit", to: "customers#quit"
    patch "/customers/out", to: "customers#out"
  end

  # 管理者用
  # URL /admin/...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :items, only: [:new, :create, :show, :index, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  ## 消費税を求めるメソッド
  def with_tax_price
      (price * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :genre_id, :name, :introduction, :price, :is_active)
  end


end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h1>商品編集</h1>
  <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
    <h4>商品画像</h4>
      <%= f.file_field :item_image, accept: "image/*" %>
    <h4>商品名</h4>
      <%= f.text_field :name %>
    <h4>商品説明</h4>
      <%= f.text_area :introduction %>
    <h4>ジャンル</h4>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択してください" %>
    <h4>税抜価格</h4>
      <%= f.text_field :price %>
    <h4>販売ステータス</h4>
      <%= f.radio_button :is_active, true, checked: true %>
      <%= f.label :"販売中" %>

      <%= f.radio_button :is_active, false %>
      <%= f.label :"販売停止中" %>

    <%= f.submit "新規登録" %>
  <% end %>

app/views/admin/items/index.html.erb
 <h5>商品一覧</h5>

<% @items.each do |item| %>
<div>
  <p>商品ID<%= item.id %></p>
  <%= link_to admin_item_path(item.id) do %>
    <p><%= item.name %></p>
  <% end %>
  <p>税抜価格<%= item.price %></p>
  <p>ジャンル<%#= item.genre.name %></p>
  <p>
    ステータス
    <% if item.is_active == true %>
      <span>販売中</span>
    <% else %>
      <span>>販売停止中</span>
    <% end %>
  </p>
</div>
<% end %>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
  <%= form_with model: @item, url: admin_items_path do |f| %>
    <h4>商品画像</h4>
      <%= f.file_field :item_image, accept: "image/*" %>
    <h4>商品名</h4>
      <%= f.text_field :name %>
    <h4>商品説明</h4>
      <%= f.text_area :introduction %>
    <h4>ジャンル</h4>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択してください" %>
    <h4>税抜価格</h4>
      <%= f.text_field :price %>
    <h4>販売ステータス</h4>
      <%= f.radio_button :is_active, true, checked: true %>
      <%= f.label :"販売中" %>

      <%= f.radio_button :is_active, false %>
      <%= f.label :"販売停止中" %>

    <%= f.submit "新規登録" %>
  <% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細</h1>
<div>
  <%= image_tag @item.item_image, size: "290x200" %>
  <p>商品名<%= @item.name %></p>
  <p>商品説明<%= @item.introduction%></p>
  <p>ジャンル<%= @item.genre.name %></p>
  <p>税抜価格<%= @item.price %></p>
  <p>
    販売ステータス
    <% if @item.is_active == true %>
      <span>販売中</span>
    <% else %>
      <span>>販売停止中</span>
    <% end %>
  </p>
  <%= link_to "編集する", edit_admin_item_path(@item.id) %>
</div>