config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about", to: "public/homes#about"

  # 顧客用
  # URL /customers/...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  scope module: :public do
    resources :delivery_addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:show, :index]
    resources :cart_items, only: [:create, :index, :update, :destroy]
    delete "/cart_items/destroy_all", to: "cart_items#destroy_all"
    resources :orders, only: [:new, :create, :index, :show]
    get "/orders/comfirm", to: "order#/comfirm"
    get "/orders/complete", to: "orders#complete"
    get "/customers/my_page", to: "customers#show"
    get "/customers/information/edit", to: "customers#edit"
    patch "/customers/information", to: "customers#update"
    get "/customers/quit", to: "customers#quit"
    patch "/customers/out", to: "customers#out"
  end

  # 管理者用
  # URL /admin/...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :items, only: [:new, :create, :show, :index, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">

<h2>ジャンル編集</h2>

<%= form_with model: @genre, url:admin_genre_path do |f| %>
  <label>ジャンル名</label>
  <%= f.text_field :name %>
  <%= f.submit "変更を保存", :class => "btn btn-primary" %>
<% end %>

</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h5>ジャンル一覧・追加</h5>
    </div>
  </div>

  <div class="row">
    <div class="col">
    <%= form_with model: @genre, url:admin_genres_path do |f| %>
      <div class="form-group">
        <%= f.label "ジャンル名", class: "col-form-label" %>
        <%= f.text_field :name, :placeholder => "ジャンル名" %>
        <%= f.submit "新規登録", class: "btn btn-primary" %>
      </div>
    <% end %>
    </div>
  </div>

  <div class="row">
      <div class="col">
        <table class="table">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th colspan="1"></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), :class => "btn btn-primary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
</div>