config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "/about", to: "public/homes#about"

  # 顧客用
  # URL /customers/...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  scope module: :public do
    resources :delivery_addresses, only: [:create, :index, :edit, :update, :destroy]
    resources :items, only: [:show, :index]
    resources :cart_items, only: [:create, :index, :update, :destroy]
    delete "/cart_items/destroy_all", to: "cart_items#destroy_all"
    resources :orders, only: [:new, :create, :index, :show]
    get "/orders/comfirm", to: "order#/comfirm"
    get "/orders/complete", to: "orders#complete"
    get "/customers/my_page", to: "customers#show"
    get "/customers/information/edit", to: "customers#edit"
    patch "/customers/information", to: "customers#update"
    get "/customers/quit", to: "customers#quit"
    patch "/customers/out", to: "customers#out"
  end

  # 管理者用
  # URL /admin/...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :items, only: [:new, :create, :show, :index, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  ## 小計を求めるメソッド
  def subtotal
      item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :delivery_addresses, dependent: :destroy

end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
  belongs_to :customer
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image
  has_many :cart_items, dependent: :destroy
  belongs_to :genre

  ## 消費税を求めるメソッド
  def with_tax_price
      (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :last_name_kana, :first_name, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :genre_id, :name, :introduction, :price, :is_active)
  end


end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
    keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ec</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if customer_signed_in? %>
        <ul class="navbar navbar-expand-lg">
          <div class="welcome text-light">ようこそ、<%= current_customer.last_name %>さん！</div>
        </ul>

        <ul class="nav col-6 col-sm-auto col-lg-auto my-2 justify-content-end my-md-0">
        <li class="nav-item">
          <%= link_to "マイページ", customers_my_page_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>

        <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>

        <li class="nav-item">
          <%#= link_to "カート", cart_items_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>

        <li class="nav-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
        </li>
      </ul>

      <% elsif admin_signed_in? %>
        <ul class="nav col-6 col-sm-3 col-lg-auto my-2 justify-content-center my-md-0">
          <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
          </li>

          <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
          </li>

          <li class="nav-item">
            <%#= link_to "注文履歴一覧", admins_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
          </li>

          <li class="nav-item">
            <%#= link_to "ジャンル一覧", admin_genres_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
          </li>

          <li class="nav-item">
            <%= link_to "ログアウト",  destroy_admin_session_path, method: :delete, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
          </li>
        </ul>

      <% else %>
        <div class="row">
          <div class="col-md">
            <ul class="nav col-6 col-sm-3 col-lg-auto my-2 justify-content-end my-md-0">
              <li class="nav-item">
                <%= link_to "About", about_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "商品一覧", items_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: 'mx-1 nav-link btn btn-light btn-sm mr-2' %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>

    </header>
    <%= yield %>
  </body>
</html>